### ISSUE TITLE
alignSelf Spinner

### ISSUE THREAD

**Issue by club9822** [SimformSolutionsPvtLtd/react-native-spinner-button#11]
please set alignSelf:'center'  in    SpinnerComponent for all cases
switch (spinnerType) {
    case 'BallIndicator':
      return (
        <View style={{ width: width, alignItems: 'center', justifyContent: 'center' }}>  /// here    for all //case
    ///   ..
        </View>
      );
    case 'BarIndicator':
   .....

for be center in show loading spinner

**Comment by Krunal-K-SimformSolutions** [comment]
@club9822: We updated the package! Appreciate your support!
