### ISSUE TITLE
Tried to register two views with the same name RNSVGRect, js engine: hermes

### ISSUE THREAD

**Issue by NemugaDev** [SimformSolutionsPvtLtd/react-native-spinner-button#44]
ERROR  Error: Requiring module "node_modules\react-native-spinner-button\index.js", which threw an exception: Invariant Violation: 
Tried to register two views with the same name RNSVGRect, js engine: hermes.
I Keept getting that error. here are dependancies.
  "dependencies": {
    "@react-navigation/bottom-tabs": "^6.5.11",
    "@react-navigation/drawer": "^6.6.6",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/stack": "^6.3.20",
    "nativewind": "^2.0.11",
    "react": "18.1.0",
    "react-native": "0.70.14",
    "react-native-dimension": "^1.0.6",
    "react-native-elements": "^3.4.3",
    "react-native-feather": "^1.1.2",
    "react-native-floating-label-input": "^1.4.3",
    "react-native-gesture-handler": "^2.14.0",
    "react-native-paper": "^5.11.4",
    "react-native-reanimated": "^3.6.1",
    "react-native-safe-area-context": "^4.7.4",
    "react-native-screens": "^3.27.0",
    "react-native-spinner-button": "^1.4.0",
    "react-native-svg": "^14.1.0",
    "react-native-vector-icons": "^10.0.2"
  }
.

**Comment by rommyarb** [comment]
Why closed?

**Comment by mukesh-simform** [comment]
@rommyarb New version has been released, Please have a look to that https://www.npmjs.com/package/react-native-spinner-button/v/1.4.3

You can reopen this if you're still facing the same. Thank you!

**Comment by GunnarAK** [comment]
This issue is still persisting in 1.4.3

my env:
```
├── expo@51.0.38
├── react-native-spinner-button@1.4.3
├── react-native-svg@15.2.0
├── react-native-gradients@2.1.1
├── react-native@0.74.5
```

**Comment by MS0015** [comment]
This issue is still persisting in 1.4.3

 "react-native-svg": "^15.8.0",
 "react-native": "0.76.0",
